version: 'latest'

services:
  zookeeper-01:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-01
    container_name: zookeeper-01
    networks:
      - book-social-network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  zookeeper-02:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-02
    container_name: zookeeper-02
    networks:
      - book-social-network
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182

  zookeeper-03:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-03
    container_name: zookeeper-03
    networks:
      - book-social-network
    ports:
      - "2183:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183

  kafka-broker-01:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-broker-01
    container_name: kafka-broker-01
    networks:
      - book-social-network
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-01:2181,zookeeper-02:2181,zookeeper-03:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-01:9092,EXTERNAL://${DOCKER_HOST_IP:-localhost}:9094,DOCKER://host.docker.internal:29092
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_JMX_PORT: 9999
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

  kafka-broker-02:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-broker-02
    container_name: kafka-broker-02
    networks:
      - book-social-network
    ports:
      - "9093:9092"
      - "29093:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-01:2181,zookeeper-02:2181,zookeeper-03:2181
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-02:9093,EXTERNAL://${DOCKER_HOST_IP:-localhost}:9095,DOCKER://host.docker.internal:29093
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_JMX_PORT: 9999
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

networks:
  book-social-network:
    name: book-social-network
    driver: bridge