server:
  port: 8888

app:
  services:
    identity: http://localhost:8080/identity/api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=/identity/**
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-profile/api/v1/profile/**