server:
  port: 8888

clients:
  identity:
    host: http://localhost:8080/identity/api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=/identity/**
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-profile/api/v1/profile/**
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notification/api/v1/**
        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=/post/api/v1/**