server:
  port: 8083
  servlet:
    context-path: /post/api

spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:Theluong1503@localhost:27017/notification-service?authSource=admin
