server:
  port: 8081
  servlet:
    context-path: /user-profile/api

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: Theluong1503

clients:
  identity:
    client-id: booksn_app
    client-secret: BLw0XorhrGQoPPk78OBsmlCE5T1E4Ggl
    url: http://localhost:8180