server:
  port: 8080
  servlet:
    context-path: /identity/api

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:Theluong1503}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

jwt:
  secret-key: ${SECRET_KEY:uz85j9Ka41OK2jQEY0z8C6cC0hsHzRo1jMyfvYY0iU9MkwO2xdyU+T7GkFI87lji}

clients:
  profile:
    host: ${PROFILE_HOST:http://localhost:8081/user-profile}
    create-profile-path: /v1/internal-profile

